'use strict';

(function () {
  var PHOTOS_COUNTER = 25;
  var AVATAR_DESCRIPTION_COUNTER = 6;

  var DESCRIPTION_MAX_LENGTH = 140;

  var HASHTAG_MAX_LENGTH = 20;

  var LETTER_NUMBER = /^[0-9a-zA-ZаАбБвВгГдДеЕёЁжЖзЗиИйЙкКлЛмМнНоОпПрРсСтТуУфФхХцЦчЧшШщЩъЪыЫьЬэЭюЮяЯ]+$/;

  var ENTER_KEY_CODE = 13;
  var ESC_KEY_CODE = 27;

  window.data = {
    PHOTOS_COUNTER: PHOTOS_COUNTER,
    AVATAR_DESCRIPTION_COUNTER: AVATAR_DESCRIPTION_COUNTER,
    DESCRIPTION_MAX_LENGTH: DESCRIPTION_MAX_LENGTH,
    HASHTAG_MAX_LENGTH: HASHTAG_MAX_LENGTH,
    LETTER_NUMBER: LETTER_NUMBER,
    ENTER_KEY_CODE: ENTER_KEY_CODE,
    ESC_KEY_CODE: ESC_KEY_CODE
  };
})();
