'use strict';

(function () {
  var LIKES_MIN_NUMBER = 15;
  var LIKES_MAX_NUMBER = 200;

  var COMMENTS_MIN_NUMBER = 1;
  var COMMENTS_MAX_NUMBER = 15;

  var PHOTOS_COUNTER = 25;
  var AVATAR_DESCRIPTION_COUNTER = 6;

  var DESCRIPTION_MAX_LENGTH = 140;

  var HASHTAG_MAX_LENGTH = 20;

  var LETTER_NUMBER = /^[0-9a-zA-ZаАбБвВгГдДеЕёЁжЖзЗиИйЙкКлЛмМнНоОпПрРсСтТуУфФхХцЦчЧшШщЩъЪыЫьЬэЭюЮяЯ]+$/;

  var ENTER_KEY_CODE = 13;
  var ESC_KEY_CODE = 27;

  var StatusCode = {
    OK: 200,
    BAD: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUEST: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    PROXY_AUTHENTICATION_REQUIRED: 407,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    GONE: 410,
    IM_A_TEAPOT: 418,
    TOO_MANY_REQUESTS: 429,
    UNAVAILABLE_FOR_LEGAL_REASONS: 451,
    CLIENT_CLOSED_REQUEST: 499,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTER: 501,
    BAD_GETAWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEAWAY_TIMEOUT: 504,
    HTTP_VERSION_NOT_SUPPORTED: 505,
    VARIANT_ALSO_NEGOTIATES: 506,
    INSUFFICIENT_STORAGE: 507,
    LOOP_DETECTED: 508,
    BANDWIDTH_LIMIT_EXCEEDED: 509,
    NOT_EXTENDED: 510,
    NETWORK_AUTHENTICATION_REQUIRED: 511,
    UNKNOWN_ERROR: 520,
    WEB_SERVER_IS_DOWN: 521,
    CONNECTION_TIMED_OUT: 522,
    ORIGIN_IS_UNREACHABLE: 523,
    A_TIMEOUT_OCCURED: 524,
    SSL_HANDSHAKE_FAILED: 525,
    INVALID_SSL_CERTIFICATE: 526
  };

  window.data = {
    LIKES_MIN_NUMBER: LIKES_MIN_NUMBER,
    LIKES_MAX_NUMBER: LIKES_MAX_NUMBER,
    COMMENTS_MIN_NUMBER: COMMENTS_MIN_NUMBER,
    COMMENTS_MAX_NUMBER: COMMENTS_MAX_NUMBER,
    PHOTOS_COUNTER: PHOTOS_COUNTER,
    AVATAR_DESCRIPTION_COUNTER: AVATAR_DESCRIPTION_COUNTER,
    DESCRIPTION_MAX_LENGTH: DESCRIPTION_MAX_LENGTH,
    HASHTAG_MAX_LENGTH: HASHTAG_MAX_LENGTH,
    LETTER_NUMBER: LETTER_NUMBER,
    ENTER_KEY_CODE: ENTER_KEY_CODE,
    ESC_KEY_CODE: ESC_KEY_CODE,
    STATUS_CODE: StatusCode
  };
})();
